---

- name: Add repo file
  template: src=mariadb_centos.repo.j2 dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644

- name: Install MariaDB
  yum: name={{ item }} enablerepo=mariadb state=present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: update pip
  command: pip install --upgrade pip

- name: Install the python MySQLdb module
  pip: name={{ item }}
  with_items:
  - MySQL-python
  - pexpect

- name: pull down Dad Data
  copy: src=../../../../aws_user dest=/home/{{user_name}}

- name: Enable and start MySQL
  service: name=mysql state=started enabled=yes

  mysql_user: name=remote_poller host="%" password={{ extra_password }} priv=*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP

- name: create community outpost db
  mysql_db: name=outpost_db state=present

- name: create table by importing sql
  mysql_db: name=outpost_db state=import target=../../../../mysql/create_table.sql

