---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install needed yum packages
  yum: 
    name: '{{ item }}'
    state: latest
    with_items:
      - vim
      - python-pip
      - gcc
      - python-devel
      - mysql-devel
 

