---

- name: set up target server(s) to be able to run the MariaDB server
  hosts: all # limit from set of hosts using a commandline variable - jenkins jobs are config'ed to do this
  become: no
  
  roles:
    - install_packages # first do basic updates + package installs
    - bbb_role  # then do VNOSA- specific provisioning
